[package]
name = "aquatunnel"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
glam = "0.30.1"
legion = "0.4.0"
rapier2d = "0.24.0"
sdl2 = {version = "0.37.0", features = ["ttf", "image"]}
